Repository cda-tum/dd_package, pull requests merged in 2023-03, with the labels that each got.

#142 functionized UniqueTable search
  include/dd/UniqueTable.hpp
Labels: enhancement

#144 ✨ Two-Qubit Gate Extensions
  include/dd/GateMatrixDefinitions.hpp
  include/dd/Package.hpp
  test/test_package.cpp
Labels: enhancement

#146 🩹 Use fixed-width integer types
  include/dd/Definitions.hpp
  include/dd/Export.hpp
  include/dd/Package.hpp
  include/dd/StochasticNoiseOperationTable.hpp
  test/test_package.cpp
Labels: bug

#148 fixed inner product not conjugating top edge weight
  include/dd/Package.hpp
Labels: bug, documentation

#150 fixed inner product bug and created test case
  include/dd/Package.hpp
  test/test_package.cpp
Labels: bug
